name: Example

on:
  repository_dispatch:
    types: [org-workflow-push]  
   
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.event.ref }}
        #ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: LS
      run: |
        git status
        ls -R
        echo ${{ github.event.client_payload.event.ref }}
      shell: bash
